import Foundation

enum CAMLSerializer {
    private static let header = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by CAPlayground https://caplayground.vercel.app -->
"""

    static func serialize(project: CAProjectDocument, document: AnimationDocument, kind: CADocumentKind) -> String {
        let wallpaper = kind == .wallpaper
        let serializedRoot = wallpaper ? layer(document.root, indent: 1) : wrapper(root: document.root)
        let stateXML = wallpaper ? "" : states(document, root: document.root)
        return header + "\n<caml xmlns=\"http://www.apple.com/CoreAnimation/1.0\">\n\(serializedRoot)\(stateXML)\n</caml>"
    }

    private static func wrapper(root: LayerModel) -> String {
        let wrapper = LayerModel(id: UUID(), name: "CAPlayground Root Layer", kind: .basic,
                                 children: [root], position: root.position, size: root.size, geometryFlipped: false)
        return layer(wrapper, indent: 1)
    }

    private static func layer(_ model: LayerModel, indent: Int) -> String {
        let tag: String = switch model.kind {
        case .gradient: "CAGradientLayer"; case .emitter: "CAEmitterLayer"; case .transform: "CATransformLayer"
        case .replicator: "CAReplicatorLayer"; case .text: "CATextLayer"; default: "CALayer"
        }
        var attributes: [(String, String?)] = [
            ("id", model.id.uuidString), ("name", model.name), ("bounds", "0 0 \(number(model.size.width)) \(number(model.size.height))"),
            ("position", "\(number(model.position.x)) \(number(model.position.y))"), ("anchorPoint", "\(number(model.anchorPoint.x)) \(number(model.anchorPoint.y))"),
            ("zPosition", model.zPosition == 0 ? nil : number(model.zPosition)), ("opacity", model.opacity == 1 ? nil : number(model.opacity)),
            ("speed", model.speed == 1 ? nil : number(model.speed)), ("cornerRadius", model.cornerRadius == 0 ? nil : number(model.cornerRadius)),
            ("masksToBounds", model.masksToBounds ? "1" : nil), ("geometryFlipped", model.geometryFlipped ? "1" : nil),
            ("backgroundColor", model.backgroundColor.flatMap(color)), ("borderColor", model.borderColor.flatMap(color)),
            ("borderWidth", model.borderWidth == 0 ? nil : number(model.borderWidth)), ("compositingFilter", model.blendMode)
        ]
        var transforms: [String] = []
        if model.scale != 1 { transforms.append("scale(\(number(model.scale)))") }
        if model.rotationX != 0 { transforms.append("rotateX(\(number(model.rotationX))deg)") }
        if model.rotationY != 0 { transforms.append("rotateY(\(number(model.rotationY))deg)") }
        if model.rotation != 0 { transforms.append("rotate(\(number(model.rotation))deg)") }
        if !transforms.isEmpty { attributes.append(("transform", transforms.joined(separator: " "))) }
        if model.kind == .text { attributes += [("string", model.text), ("fontSize", model.fontSize.map(number)), ("foregroundColor", model.textColor.flatMap(color)), ("alignmentMode", model.textAlignment), ("wrapped", (model.wrapsText ?? true) ? "1" : "0")] }
        if model.kind == .image { attributes += [("contents", model.imageName.map { "assets/\($0)" }), ("contentsGravity", gravity(model.contentMode))] }
        if model.kind == .replicator { attributes += [("instanceCount", String(model.instanceCount ?? 1)), ("instanceDelay", model.instanceDelay.map(number)), ("instanceTransform", instanceTransform(model)), ("instanceColor", "1 1 1"), ("preservesDepth", "1")] }
        if (model.kind == .transform || model.kind == .replicator), let perspective = model.perspective { attributes.append(("sublayerTransform", "perspective(\(number(perspective)))")) }
        if model.kind == .emitter { attributes += [("emitterPosition", model.emitterPosition.map { "\(number($0.x)) \(number($0.y))" }), ("emitterSize", model.emitterSize.map { "\(number($0.width)) \(number($0.height))" }), ("emitterShape", model.emitterShape), ("emitterMode", model.emitterMode), ("renderMode", model.renderMode)] }
        let pad = String(repeating: "  ", count: indent)
        let attrs = attributes.compactMap { key, value in value.map { " \(key)=\"\(escape($0))\"" } }.joined()
        var children = ""
        if model.kind == .gradient, let stops = model.gradientStops {
            children += "\n\(pad)  <colors>" + stops.map { "\n\(pad)    <CGColor value=\"\(color($0.color) ?? "1 1 1")\" opacity=\"\(number($0.opacity))\"/>" }.joined() + "\n\(pad)  </colors>"
            children += "\n\(pad)  <type value=\"\(escape(model.gradientType ?? "axial"))\"/>"
        }
        if !model.animations.isEmpty { children += animations(model.animations, indent: indent + 1) }
        if !model.children.isEmpty { children += "\n\(pad)  <sublayers>" + model.children.map { "\n" + layer($0, indent: indent + 2) }.joined() + "\n\(pad)  </sublayers>" }
        if model.kind == .emitter, let cells = model.emitterCells, !cells.isEmpty { children += emitterCells(cells, indent: indent + 1) }
        return children.isEmpty ? "\(pad)<\(tag)\(attrs)/>" : "\(pad)<\(tag)\(attrs)>\(children)\n\(pad)</\(tag)>"
    }

    private static func animations(_ animations: [KeyframeAnimationModel], indent: Int) -> String {
        let pad = String(repeating: "  ", count: indent)
        return "\n\(pad)<animations>" + animations.filter(\.enabled).map { animation in
            let values = animation.numericValues.map(number).joined(separator: " ")
            let times = animation.keyTimes.map(number).joined(separator: " ")
            return "\n\(pad)  <CAKeyframeAnimation keyPath=\"\(escape(animation.keyPath))\" duration=\"\(number(animation.duration))\" values=\"\(values)\" keyTimes=\"\(times)\" repeatCount=\"\(animation.repeats ? "inf" : "0")\" autoreverses=\"\(animation.autoreverses ? "1" : "0")\" calculationMode=\"\(animation.calculationMode)\"/>"
        }.joined() + "\n\(pad)</animations>"
    }

    private static func states(_ document: AnimationDocument, root: LayerModel) -> String {
        let names = document.states.filter { !$0.lowercased().hasPrefix("base") }
        let stateXML = names.map { name in
            let overrides = document.stateOverrides[name] ?? []
            let elements = overrides.map { value in
                let encoded: (String, String) = switch value.value { case .number(let number): (number.rounded() == number ? "integer" : "real", self.number(value.keyPath == "transform.rotation.z" ? number * .pi / 180 : number)); case .string(let string): (value.keyPath == "backgroundColor" ? "CGColor" : "string", value.keyPath == "backgroundColor" ? (color(string) ?? "1 1 1") : string) }
                return "        <LKStateSetValue targetId=\"\(value.targetID.uuidString)\" keyPath=\"\(escape(value.keyPath))\"><value type=\"\(encoded.0)\" value=\"\(escape(encoded.1))\"/></LKStateSetValue>"
            }.joined(separator: "\n")
            return "    <LKState name=\"\(escape(name))\"><elements>\n\(elements)\n      </elements></LKState>"
        }.joined(separator: "\n")
        let transitionXML = document.stateTransitions.map { transition in
            let elements = transition.elements.map { element in
                guard let spring = element.animation else { return "        <LKStateTransitionElement targetId=\"\(element.targetID.uuidString)\" key=\"\(escape(element.keyPath))\"/>" }
                return "        <LKStateTransitionElement targetId=\"\(element.targetID.uuidString)\" key=\"\(escape(element.keyPath))\"><animation type=\"CASpringAnimation\" damping=\"\(number(spring.damping))\" mass=\"\(number(spring.mass))\" stiffness=\"\(number(spring.stiffness))\" velocity=\"\(number(spring.initialVelocity))\"/></LKStateTransitionElement>"
            }.joined(separator: "\n")
            return "    <LKStateTransition fromState=\"\(escape(transition.fromState))\" toState=\"\(escape(transition.toState))\"><elements>\n\(elements)\n      </elements></LKStateTransition>"
        }.joined(separator: "\n")
        return "\n    <states>\n\(stateXML)\n    </states>\n    <stateTransitions>\n\(transitionXML)\n    </stateTransitions>"
    }

    private static func emitterCells(_ cells: [EmitterCellModel], indent: Int) -> String {
        let pad = String(repeating: "  ", count: indent)
        return "\n\(pad)<emitterCells>" + cells.map { cell in "\n\(pad)  <CAEmitterCell name=\"\(escape(cell.name))\" birthRate=\"\(number(cell.birthRate))\" lifetime=\"\(number(cell.lifetime))\" lifetimeRange=\"\(number(cell.lifetimeRange))\" velocity=\"\(number(cell.velocity))\" velocityRange=\"\(number(cell.velocityRange))\" scale=\"\(number(cell.scale))\" scaleRange=\"\(number(cell.scaleRange))\" alphaSpeed=\"\(number(cell.alphaSpeed))\"/>" }.joined() + "\n\(pad)</emitterCells>"
    }

    private static func color(_ hex: String) -> String? { var value = hex; if value.first == "#" { value.removeFirst() }; guard value.count >= 6, let raw = UInt64(value.prefix(6), radix: 16) else { return nil }; return "\(number(Double((raw >> 16) & 255) / 255)) \(number(Double((raw >> 8) & 255) / 255)) \(number(Double(raw & 255) / 255))" }
    private static func number(_ value: Double) -> String { value.rounded() == value ? String(Int(value)) : String(format: "%.5f", value).replacingOccurrences(of: #"0+$"#, with: "", options: .regularExpression).replacingOccurrences(of: #"\.$"#, with: "", options: .regularExpression) }
    private static func escape(_ value: String) -> String { value.replacingOccurrences(of: "&", with: "&amp;").replacingOccurrences(of: "\"", with: "&quot;").replacingOccurrences(of: "<", with: "&lt;").replacingOccurrences(of: ">", with: "&gt;") }
    private static func gravity(_ fit: String?) -> String { switch fit { case "contain": "resizeAspect"; case "cover": "resizeAspectFill"; case "none": "center"; default: "resize" } }
    private static func instanceTransform(_ model: LayerModel) -> String? { var parts: [String] = []; if (model.instanceTranslationX ?? 0) != 0 || (model.instanceTranslationY ?? 0) != 0 || (model.instanceTranslationZ ?? 0) != 0 { parts.append("translate(\(number(model.instanceTranslationX ?? 0)), \(number(model.instanceTranslationY ?? 0)), \(number(model.instanceTranslationZ ?? 0)))") }; if (model.instanceRotation ?? 0) != 0 { parts.append("rotate(\(number(model.instanceRotation ?? 0))deg)") }; return parts.isEmpty ? nil : parts.joined(separator: " ") }
}
